    INSERT INTO LOAN_PRODUCT (LOAN_PRODUCT_ID,LOAN_PRODUCT_NAME,VARIABLE_INTEREST_RATE)
    VALUES (1,'Fixed Rate Product',FALSE);

    INSERT INTO LOAN_PRODUCT (LOAN_PRODUCT_ID,LOAN_PRODUCT_NAME,VARIABLE_INTEREST_RATE)
    VALUES (2,'Variable Rate Product',TRUE);